#cloud-config

runcmd:
  - sudo apt update
  - sudo apt install software-properties-common -y
  - sudo add-apt-repository --yes --update ppa:ansible/ansible
  - sudo apt install ansible -y
  - sed -i 's/#PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config   # echo will not replace - it will append
  - sudo systemctl restart sshd   # sudo needed

users:
  - default  # I think this points to ubuntu user on ubuntu OS
  - name: ansible     # hyphen given only before name
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL   ## not reflecting
    plain_text_passwd: 'ansible'  # Authentication failure
    lock_passwd: false   ## 





# hashing a password is not the ideal way of concealing it