#cloud-config

runcmd:
  - sudo apt update
  - sudo apt install software-properties-common -y
  - sudo add-apt-repository --yes --update ppa:ansible/ansible
  - sudo apt install ansible -y
  - echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config   ## this is not replacing it 
  - sudo systemctl restart sshd   # sudo needed

users:
  - default  # I think this points to ubuntu user on ubuntu OS
  - name: ansible     # hyphen given only before name
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    plain_text_passwd: 'ansible'  # Authentication failure
    lock_passwd: false   # check if this change lets you login with password





# hashing a password is not the ideal way of concealing it