#cloud-config

# not pushing any keys from local system --> will run ansible playbooks with password prompt until figuring out a better solution

users:
  - default  # I think this points to ubuntu (default) user on ubuntu OS
  - name: ansible     # hyphen given only before name
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL   ## sudoers file will not show an entry on ansible user. May be that's why ansible user is added to the group "sudo" --> check the line below
    groups: sudo    # adding ansible user to group sudo --> by default this group is given sudo privileges --> as seen in sudoers file.
    plain_text_passwd: 'ansible'  # Authentication failure
    lock_passwd: false   ## setting this true will give Authentication failure when you do su - ansible & give password


runcmd:
  - sudo apt update
  - sudo apt install software-properties-common -y
  - sudo add-apt-repository --yes --update ppa:ansible/ansible
  - sudo apt install ansible -y
  - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config   # setting this to yes will let you login as "ssh ansible@ip" using password authentication
  - sudo systemctl restart sshd   # sudo needed
  #
  # setting up data-lv on 2nd disk:
  - sudo pvcreate /dev/xvdg /dev/xvdh     # leaving /dev/xvdc unallocated
  - sudo vgcreate datavg /dev/xvdg               # this vg will be created with entire space of the given pv (xvdg) automatically
  - sudo lvcreate -l 95%FREE  -n datalv datavg
  - sudo mkfs.ext4 /dev/datavg/datalv
  - sudo mkdir /app
  - echo /dev/datavg/datalv  /app  ext4  defaults  0 0 >> /etc/fstab     # while testing it needs sudo permissions but cloud-init did it without sudo
  - sudo mount -a


# hashing a password is not the ideal way of concealing it