# Never write this file without manually testing the commands 1st

#cloud-config
write_files: 
  - path: /run/myserver/index.html
    owner: root:root
    permissions: "0644"
    content: "<h1>cloud init was here</h1>"
runcmd:
  - sudo apt update           # without this, nginx installation was failing
  - sudo apt install nginx -y
  - mv /run/myserver/index.html /usr/share/nginx/html/index.html
  - systemctl enable --no-block nginx 
  - systemctl start --no-block nginx 